### ISSUE TITLE
shift+enter for Send button not possible

### ISSUE THREAD

**Issue by vpet98** [EIDA/a10y#12]
It seems shift+enter key binding is not available in textual. We need to choose another for sending request. For now I will use ctrl+s (s for send).

You can see below the available keys and choose another:

  Escape = "escape" 
  ShiftEscape = "shift+escape"
  Return = "return"
  ControlAt = "ctrl+@" 
  ControlA = "ctrl+a"
  ControlB = "ctrl+b"
  ControlC = "ctrl+c"
  ControlD = "ctrl+d"
  ControlE = "ctrl+e"
  ControlF = "ctrl+f"
  ControlG = "ctrl+g"
  ControlH = "ctrl+h"
  ControlI = "ctrl+i" 
  ControlJ = "ctrl+j" 
  ControlK = "ctrl+k"
  ControlL = "ctrl+l"
  ControlM = "ctrl+m" 
  ControlN = "ctrl+n"
  ControlO = "ctrl+o"
  ControlP = "ctrl+p"
  ControlQ = "ctrl+q"
  ControlR = "ctrl+r"
  ControlS = "ctrl+s"
  ControlT = "ctrl+t"
  ControlU = "ctrl+u"
  ControlV = "ctrl+v"
  ControlW = "ctrl+w"
  ControlX = "ctrl+x"
  ControlY = "ctrl+y"
  ControlZ = "ctrl+z"
  Control1 = "ctrl+1"
  Control2 = "ctrl+2"
  Control3 = "ctrl+3"
  Control4 = "ctrl+4"
  Control5 = "ctrl+5"
  Control6 = "ctrl+6"
  Control7 = "ctrl+7"
  Control8 = "ctrl+8"
  Control9 = "ctrl+9"
  Control0 = "ctrl+0"
  ControlShift1 = "ctrl+shift+1"
  ControlShift2 = "ctrl+shift+2"
  ControlShift3 = "ctrl+shift+3"
  ControlShift4 = "ctrl+shift+4"
  ControlShift5 = "ctrl+shift+5"
  ControlShift6 = "ctrl+shift+6"
  ControlShift7 = "ctrl+shift+7"
  ControlShift8 = "ctrl+shift+8"
  ControlShift9 = "ctrl+shift+9"
  ControlShift0 = "ctrl+shift+0"
  ControlBackslash = "ctrl+backslash"
  ControlSquareClose = "ctrl+right_square_bracket"
  ControlCircumflex = "ctrl+circumflex_accent"
  ControlUnderscore = "ctrl+underscore"
  Left = "left"
  Right = "right"
  Up = "up"
  Down = "down"
  Home = "home"
  End = "end"
  Insert = "insert"
  Delete = "delete"
  PageUp = "pageup"
  PageDown = "pagedown"
  ControlLeft = "ctrl+left"
  ControlRight = "ctrl+right"
  ControlUp = "ctrl+up"
  ControlDown = "ctrl+down"
  ControlHome = "ctrl+home"
  ControlEnd = "ctrl+end"
  ControlInsert = "ctrl+insert"
  ControlDelete = "ctrl+delete"
  ControlPageUp = "ctrl+pageup"
  ControlPageDown = "ctrl+pagedown"
  ShiftLeft = "shift+left"
  ShiftRight = "shift+right"
  ShiftUp = "shift+up"
  ShiftDown = "shift+down"
  ShiftHome = "shift+home"
  ShiftEnd = "shift+end"
  ShiftInsert = "shift+insert"
  ShiftDelete = "shift+delete"
  ShiftPageUp = "shift+pageup"
  ShiftPageDown = "shift+pagedown"
  ControlShiftLeft = "ctrl+shift+left"
  ControlShiftRight = "ctrl+shift+right"
  ControlShiftUp = "ctrl+shift+up"
  ControlShiftDown = "ctrl+shift+down"
  ControlShiftHome = "ctrl+shift+home"
  ControlShiftEnd = "ctrl+shift+end"
  ControlShiftInsert = "ctrl+shift+insert"
  ControlShiftDelete = "ctrl+shift+delete"
  ControlShiftPageUp = "ctrl+shift+pageup"
  ControlShiftPageDown = "ctrl+shift+pagedown"
  BackTab = "shift+tab"
  F1 = "f1"
  F2 = "f2"
  F3 = "f3"
  F4 = "f4"
  F5 = "f5"
  F6 = "f6"
  F7 = "f7"
  F8 = "f8"
  F9 = "f9"
  F10 = "f10"
  F11 = "f11"
  F12 = "f12"
  F13 = "f13"
  F14 = "f14"
  F15 = "f15"
  F16 = "f16"
  F17 = "f17"
  F18 = "f18"
  F19 = "f19"
  F20 = "f20"
  F21 = "f21"
  F22 = "f22"
  F23 = "f23"
  F24 = "f24"
  ControlF1 = "ctrl+f1"
  ControlF2 = "ctrl+f2"
  ControlF3 = "ctrl+f3"
  ControlF4 = "ctrl+f4"
  ControlF5 = "ctrl+f5"
  ControlF6 = "ctrl+f6"
  ControlF7 = "ctrl+f7"
  ControlF8 = "ctrl+f8"
  ControlF9 = "ctrl+f9"
  ControlF10 = "ctrl+f10"
  ControlF11 = "ctrl+f11"
  ControlF12 = "ctrl+f12"
  ControlF13 = "ctrl+f13"
  ControlF14 = "ctrl+f14"
  ControlF15 = "ctrl+f15"
  ControlF16 = "ctrl+f16"
  ControlF17 = "ctrl+f17"
  ControlF18 = "ctrl+f18"
  ControlF19 = "ctrl+f19"
  ControlF20 = "ctrl+f20"
  ControlF21 = "ctrl+f21"
  ControlF22 = "ctrl+f22"
  ControlF23 = "ctrl+f23"
  ControlF24 = "ctrl+f24"

**Comment by jschaeff** [comment]
Ok, let's go for ctrl+s :)
