### ISSUE TITLE
Add a "cancel" operation

### ISSUE THREAD

**Issue by jschaeff** [EIDA/a10y#13]
If by mistake someone issues a VERY large request, she should be able to cancel it.

**Comment by vpet98** [comment]
Added cancel operation with escape button.

After Send button is hit, if escape is pressed the following things will happen:

- The app remains responsive (this actually happens in all requests from now on).
- The request will not show results, if response wasn't fully received by the time the escape button was hit.
- A "Request is cancelled!" message will be shown in the status, **but it will appear after the request is completed** in the background. Seems not possible to completely kill the _concurrent worker_.
- The user can issue new request after hitting escape without need to wait. Just the "Request is cancelled!" message of a previous large request might come later in the status window after another request has shown results.

The fact that actually the request is executed might not be ideal. But user experience is not much affected by this.
