### ISSUE TITLE
Crash on wrong input

### ISSUE THREAD

**Issue by jschaeff** [EIDA/a10y#15]
If putting a wrong time string, the application crashes very disgracefully: 

ValueError: time data '2019-01-14' does not match format '%Y-%m-%dT%H:%M:%S'

Would be useful to validate inputs.
Maybe useful to put a warning mark or in red invalid inputs (even gray out the SEND button)

**Comment by vpet98** [comment]
The ideal here would be to know what datetime formats **exactly** the FDSN service accepts (I think nothing is mentioned in their specs pdf other than simply "datetime").

Supposing it accepts only "YYYY-MM-DDTHH:MM:SS" or "YYYY-MM-DD", the problem should be solved now.

Availability service is let to handle input validation.

**Comment by jschaeff** [comment]
You suppose correctly. It is specified in the websevice common specs, another document common to all fdsn webservices.
