### ISSUE TITLE
Be colorblilnd friendly

### ISSUE THREAD

**Issue by jschaeff** [EIDA/a10y#16]
Choose a colorbling friendly palette.

Look at this article: https://davidmathlogic.com/colorblind/

Maybe IBM palette is OK for our app ?

**Comment by vpet98** [comment]
Not all existing colors are available for use. The list of available colors is here: https://rich.readthedocs.io/en/stable/appendix/colors.html

I changed to some that seem distinguishable based on the article.
![Screenshot from 2023-12-21 12-16-47](https://github.com/EIDA/a10y/assets/57916087/644b3eee-9157-4fd6-a492-72fb2f76793d)

**Comment by jschaeff** [comment]
It looks nicer now.
