### ISSUE TITLE
Conda installation instructions

### ISSUE THREAD

**Issue by jschaeff** [EIDA/a10y#26]
Add conda installation instructions in the readme

**Comment by jschaeff** [comment]
But if someone uses conda, she does not need to build this huge executable, which is something more suitable for direct download of the program.

As a Conda user, I would expect instructions on how to download the code, build a virtual environment and execute the program. But I'm not completely sure about how conda users feel :)

As an alternative, we could also build a package that could just be installed with `pip install a10y` and deploy the executable script.

**Comment by vpet98** [comment]
I have updated the README and made a correction. To use pyinstaller, making an environment and installing all dependencies is necessary, either using python virtual environment or conda environment.
