### ISSUE TITLE
Automatic release

### ISSUE THREAD

**Issue by jschaeff** [EIDA/a10y#27]
By using github workflow, automatically build and publish the binaries in a release. 

This can be triggered when we create a new tag on the main branch for instance ?

**Comment by vpet98** [comment]
After too many attempts it's done.

When a new tag is created, the pyinstaller workflow that creates the artifacts is executed and after this another workflow that creates the release with thsese artifacts is executed.

**Comment by vpet98** [comment]
Now regarding the releases, because of some changes in the code I think I need to replace the beta with a new one (same name I guess, just update the artifacts), so that users try the latest version. Shall I?

**Comment by jschaeff** [comment]
Congratulations !
Yes, feel free to launch a new release, do not bother with the naming.
For this kind of tool I like the calver system https://calver.org/ using the seismological convention using Day of Year, which could be : 2024.015 for today
