### ISSUE TITLE
Feature request for a later release: manage virtual networks and routing

### ISSUE THREAD

**Issue by jschaeff** [EIDA/a10y#29]
User would be so excited about being able  to ask for a virtual network.

We need to think about how this can be done.

**Comment by vpet98** [comment]
In branch routing this is now supported. Also, user doesn't need to select node anymore.

I feel the routing branch can now be merged into main.

**Comment by jschaeff** [comment]
Yes, merge please, generate a new release with updated version.

Thanks !

**Comment by vpet98** [comment]
Done! Can be used and tested.

**Comment by jschaeff** [comment]
This is great ! I'll do an official announcement on Orfeus Forum.
