### ISSUE TITLE
New EIDA node: add BGS

### ISSUE THREAD

**Issue by jschaeff** [EIDA/a10y#32]
This is not urgent, just a note to not forget.

**Comment by jschaeff** [comment]
Are the nodes hard coded in a10y ? If yes, it would be cool to fetch them from the routing service for instance. Therefore, no upgrade needed when nodes change.

**Comment by vpet98** [comment]
The routing service has this: https://www.orfeus-eu.org/eidaws/routing/1/endpoints.
But only the urls without node names appear there. So I am not sure how I can skip hardcoding the nodes.

**Comment by jschaeff** [comment]
Maybe a10y should manage a local cache for the list of nodes. Because the service takes time to reply and could also be down for some reason.

So storing locally the routing might be good, with an action from the user the refresh it.

**Comment by vpet98** [comment]
Done using https://orfeus-eu.org/epb/nodes
