### ISSUE TITLE
Feature Request: show the restriction status in the interface

### ISSUE THREAD

**Issue by jschaeff** [EIDA/a10y#35]
Story:
a user should see the restriction status (open or restricted) on the streams view.

Proposition:

Add a bold and red "**(R)**" next to the stream identifier if the stream is restricted. Do not show anything for open streams.
Add a legend in the help textbox.

How to do this ?

Availability has a second endpoint "/extent" showing this information.
Lazy support: do it only at network level as, for today, only network restriction is supported.
Full support: check the restriction for each stream as the specification allows channel level restriction.

See how fetching restriction is slowing down the user experience. Could be done asynchronously, after showing the streams to the user:

1. show streams in the window with a ... in place of the restriction status. Do not allow any interaction from the user at this stage.
2. launch restriction status retrieval (with a timeout)
3. update the window, either with restriction information or with a question mark if previous step hit a timeout.

**Comment by vpet98** [comment]
Can I have a couple of restricted networks to check?

The /extent method shows restriction information in channel level. The below request returns all channels whether they are restricted or not, although the includerestricted parameter defaults to FALSE. Why does that happen?

```https://eida.gein.noa.gr/fdsnws/availability/1/extent?net=HL&starttime=2024-03-09```

**Comment by jschaeff** [comment]
As an example, you can check ZR_2020 at RESIF.

The includerestricted param does only make sense with the "/query" method. 

With /extent, the existence of the channel is advertised along it's restriction policy.

**Comment by vpet98** [comment]
In [](https://eida.gein.noa.gr/fdsnws/availability/1/query?net=HL&starttime=2024-03-09) the channels that are given as restricted by the corresponding extent request are also included.

**Comment by jschaeff** [comment]
OK, I should have double checked the spec (https://www.fdsn.org/webservices/fdsnws-availability-1.0.pdf).
`includerestricted` is also meaningful in `/extent`

So, there is an issue with the EIDA implementation of the webservice which does not seem to respect the includerestricted parameter.

**Comment by jschaeff** [comment]
Issue in wsavailability created: https://github.com/EIDA/ws-availability/issues/33

**Comment by vpet98** [comment]
Done as close as possible the way described:

Initially when results are shown there is a `┄` next to each channel meaning restriction status unknown. Then after /extent method is queried in the background, `┄` either disappears meaning open channel or is replaced by a red bold **R** meaning restricted channel.
